### ISSUE TITLE
Configure webUI

### ISSUE THREAD

**Issue by RealPeteSys** [ThePornDatabase/namer#191]
Please forgive my novice question. How can I properly configure namer to utilize the webUI aspect? I'm new to web interfaced Python. I've set the webUI flag in the config to True and have played around with IP and Port values, but nothing works. 

I either receive a ```refused to connect``` error in the browser, or the following (if change the target host IP):

```2023-04-08 09:07:19 namer  | Traceback (most recent call last):
2023-04-08 09:07:19 namer  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-04-08 09:07:19 namer  |     return _run_code(code, main_globals, None,
2023-04-08 09:07:19 namer  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2023-04-08 09:07:19 namer  |     exec(code, run_globals)
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/__main__.py", line 69, in <module>
2023-04-08 09:07:19 namer  |     main(sys.argv[1:])
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/__main__.py", line 59, in main
2023-04-08 09:07:19 namer  |     namer.watchdog.create_watcher(config).run()
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/watchdog.py", line 176, in run
2023-04-08 09:07:19 namer  |     self.__webserver = NamerWebServer(self.__namer_config, self.__command_queue)
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 166, in __init__
2023-04-08 09:07:19 namer  |     super().__init__(self.__namer_config.host, self.__namer_config.port, webroot, blueprints)
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 55, in __init__
2023-04-08 09:07:19 namer  |     self.__make_server()
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 60, in __make_server
2023-04-08 09:07:19 namer  |     self.__server = create_server(self.__app, host=self.__host, port=self.__port, clear_untrusted_proxy_headers=True)
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 78, in create_server
2023-04-08 09:07:19 namer  |     last_serv = TcpWSGIServer(
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 244, in __init__
2023-04-08 09:07:19 namer  |     self.bind_server_socket()
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 361, in bind_server_socket
2023-04-08 09:07:19 namer  |     self.bind(sockaddr)
2023-04-08 09:07:19 namer  |   File "/usr/local/lib/python3.10/dist-packages/waitress/wasyncore.py", line 396, in bind
2023-04-08 09:07:19 namer  |     return self.socket.bind(addr)
2023-04-08 09:07:19 namer  | OSError: [Errno 99] Cannot assign requested address
1969-12-31 17:00:00 namer exited with code 1
```

I've tried the default IP address as well as others (local host, etc). I haven't altered the ```web_root``` entry as I'm not sure about its behavior.

I'm running namer is a Docker container.

**Comment by RealPeteSys** [comment]
Would like to close this issue by saying it has been resolved. I was initially attempting to use the IP of the Docker container. The correct path was to use ```localhost:<port>```.

**Comment by RealPeteSys** [comment]
Would like to close this issue by saying it has been resolved. I was initially attempting to use the IP of the Docker container. The correct path was to use localhost:<port>.
