### ISSUE TITLE
AttributeError: 'types.SimpleNamespace' object has no attribute 'name'

### ISSUE THREAD

**Issue by jobu59749** [ThePornDatabase/namer#204]
First, I would like to state that I know very little about coding.  I have been searching everything to find an answer to this.  Everything was working fine until this morning when it wasn't.  No matter what file I toss into my 'watch' folder, this same error keeps coming up.  I made sure to update python and I also updated namer to the latest, and updated the config file to the latest.  Still get this error:

2023-07-29 08:54:05 | ℹ️ INFO     | ffmpeg version "6.0-essentials_build-www.gyan.dev" found
2023-07-29 08:54:05 | ℹ️ INFO     | ffprobe version "6.0-essentials_build-www.gyan.dev" found
2023-07-29 08:54:05 | ℹ️ INFO     | Start porndb scene watcher.... watching: I:\Namer\watch
2023-07-29 08:54:05 | ℹ️ INFO     | Starting server: http://0.0.0.0:6980/
2023-07-29 08:54:24 | ℹ️ INFO     | watchdog process called for BrattySis.23.07.07.Dani.Diaz.Stepsis.Stop.Staring.At.My.Dick..mkv
2023-07-29 08:54:24 | ℹ️ INFO     | Moving I:\Namer\watch\BrattySis.23.07.07.Dani.Diaz.Stepsis.Stop.Staring.At.My.Dick..mkv to I:\Namer\work\BrattySis.23.07.07.Dani.Diaz.Stepsis.Stop.Staring.At.My.Dick..mkv for processing
2023-07-29 08:54:24 | ℹ️ INFO     | Processing: I:\Namer\work\BrattySis.23.07.07.Dani.Diaz.Stepsis.Stop.Staring.At.My.Dick..mkv
2023-07-29 08:54:24 | ℹ️ INFO     | Calculating phash for file "I:\Namer\work\BrattySis.23.07.07.Dani.Diaz.Stepsis.Stop.Staring.At.My.Dick..mkv"
2023-07-29 08:54:32 | ℹ️ INFO     | Calculated hashes: {'duration': 2179, 'phash': 'd82a78de3e8bc780', 'oshash': '2bada661f9491b62'}
2023-07-29 08:54:32 | ℹ️ INFO     | Requesting GET "https://api.metadataapi.net/scenes?hash=d82a78de3e8bc780&hashType=PHASH"
2023-07-29 08:54:32 | ℹ️ INFO     | Requesting GET "https://api.metadataapi.net/scenes?parse=brattysis.2023-07-07.Dani%20Diaz%20Stepsis%20Stop%20Staring%20At%20My%20Dick&limit=25"
2023-07-29 08:54:32 | ❌ ERROR    | An error has been caught in function '__processing_thread', process 'MainProcess' (16764), thread 'Thread-2 (__processing_thread)' (23296):
Traceback (most recent call last):
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
> File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\watchdog.py", line 146, in __processing_thread
    handle(command)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\watchdog.py", line 54, in handle
    process_file(command)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\namer.py", line 179, in process_file
    search_results = match(command.parsed_file, command.config, phash=phash)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 505, in match
    results: List[ComparisonResult] = __metadata_api_lookup(file_name_parts, namer_config, phash)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 179, in __metadata_api_lookup
    results: List[ComparisonResult] = __metadata_api_lookup_type(results, name_parts, namer_config, scene_type, phash)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 158, in __metadata_api_lookup_type
    results = __update_results(results, name_parts, namer_config, scene_type=scene_type, phash=phash)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 147, in __update_results
    for match_attempt in __get_metadataapi_net_fileinfo(name_parts, namer_config, skip_date, skip_name, scene_type=scene_type):
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 468, in __get_metadataapi_net_fileinfo
    file_infos = __get_metadataapi_net_info(url, name_parts, namer_config)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 455, in __get_metadataapi_net_info
    file_infos = __metadataapi_response_to_data(json_obj, url, formatted, name_parts, namer_config)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 401, in __metadataapi_response_to_data
    found_file_info = __json_to_fileinfo(data, url, json_response, name_parts, config)
  File "C:\Users\jobu5\AppData\Local\Programs\Python\Python311\Lib\site-packages\namer\metadataapi.py", line 369, in __json_to_fileinfo
    if tag.name not in tags:
AttributeError: 'types.SimpleNamespace' object has no attribute 'name'

Any help would be really appreciated.  Let me know if you need what's in my config file or anything.  I will do my best to learn and understand as I want to correct this if it's something I did wrong.  Thank you!

**Comment by DirtyRacer1337** [comment]
API server needs update, just wait

**Comment by electblake** [comment]
glad I checked here, thought I had mis-configured something

/me subscribes to issue and tries to wait patiently 🙏🏼

**Comment by DirtyRacer1337** [comment]
Should be fixed now
