### ISSUE TITLE
'types.SimpleNamespace' object has no attribute 'site'

### ISSUE THREAD

**Issue by HighKingPhoenix** [ThePornDatabase/namer#206]
whenever i run watchdog  i get this error even after changing api keys updating, uninstalling and reinstalling the namer:

2023-08-09 20:11:23 | ❌ ERROR    | An error has been caught in function '__processing_thread', process 'MainProcess' (11116), thread 'Thread-2 (__processing_thread)' (23204):
Traceback (most recent call last):
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
> File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\watchdog.py", line 146, in __processing_thread
    handle(command)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\watchdog.py", line 54, in handle
    process_file(command)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\namer.py", line 179, in process_file
    search_results = match(command.parsed_file, command.config, phash=phash)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 505, in match
    results: List[ComparisonResult] = __metadata_api_lookup(file_name_parts, namer_config, phash)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 179, in __metadata_api_lookup
    results: List[ComparisonResult] = __metadata_api_lookup_type(results, name_parts, namer_config, scene_type, phash)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 158, in __metadata_api_lookup_type
    results = __update_results(results, name_parts, namer_config, scene_type=scene_type, phash=phash)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 147, in __update_results
    for match_attempt in __get_metadataapi_net_fileinfo(name_parts, namer_config, skip_date, skip_name, scene_type=scene_type):
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 468, in __get_metadataapi_net_fileinfo
    file_infos = __get_metadataapi_net_info(url, name_parts, namer_config)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 455, in __get_metadataapi_net_info
    file_infos = __metadataapi_response_to_data(json_obj, url, formatted, name_parts, namer_config)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 401, in __metadataapi_response_to_data
    found_file_info = __json_to_fileinfo(data, url, json_response, name_parts, config)
  File "C:\Users\kings\AppData\Local\Programs\Python\Python310\lib\site-packages\namer\metadataapi.py", line 331, in __json_to_fileinfo
    file_info.site = data.site.name
AttributeError: 'types.SimpleNamespace' object has no attribute 'site'

**Comment by DirtyRacer1337** [comment]
It's api problem, working on it

**Comment by DirtyRacer1337** [comment]
fixed
