### ISSUE TITLE
New unRAID Docker install keeps closing

### ISSUE THREAD

**Issue by OriginalFlavor** [ThePornDatabase/namer#253]
A new install on unRAID using docker can be started but then closes.
A first file is moved from watch to work, a hash starts to be generated and then the container closes.
A log file for the container is below.
The container's directory looks very empty, only the config directory and the namer.cfg within
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/namer/__main__.py", line 88, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/namer/__main__.py", line 73, in main
    namer.watchdog.create_watcher(config).run()
  File "/usr/local/lib/python3.10/dist-packages/namer/watchdog.py", line 186, in run
    self.__webserver = NamerWebServer(self.__namer_config, self.__command_queue)
  File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 178, in __init__
    super().__init__(self.__namer_config.host, self.__namer_config.port, webroot, blueprints)
  File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 60, in __init__
    self.__make_server()
  File "/usr/local/lib/python3.10/dist-packages/namer/web/server.py", line 65, in __make_server
    self.__server = create_server(self.__app, host=self.__host, port=self.__port, clear_untrusted_proxy_headers=True)
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 243, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 364, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.10/dist-packages/waitress/wasyncore.py", line 395, in bind
  set_dir_permissions: 775
    return self.socket.bind(addr)
  set_file_permissions: 664
OSError: [Errno 99] Cannot assign requested address
  set_uid: 0
  set_gid: 0
  max_performer_names: 6
  use_database: False
  database_path: /database
  use_requests_cache: True
  requests_cache_expire_minutes: 10
  override_tpdb_address: https://api.theporndb.net
  plex_hack: False
  convert_container_to: None
  path_cleanup: False
Phash:
  search_phash: True
  send_phash: False
  use_alt_phash_tool: False
  max_ffmpeg_workers: None
  use_gpu: False
Duplicate Config:
  preserve_duplicates: True
  max_desired_resolutions: -1
  desired_codec: ['hevc', 'h264']
Tagging Config:
  write_nfo: False
  enabled_tagging: False
  enabled_poster: False
  download_type: ['poster', 'background', 'performer']
  enable_metadataapi_genres: False
  default_genre: Adult
  language: eng
  mark_collected: False
Watchdog Config:
  ignored_dir_regex: .*_UNPACK_.*
  min_file_size: 300
  del_other_files: False
  new_relative_path_name: {full_site}/{full_site} - {date} - {name} [WEBDL-{resolution}].{ext}
  watch_dir: /media/watch
  work_dir: /media/work
  failed_dir: /media/failed
  dest_dir: /media/DESTINATION
  retry_time: 
  extra_sleep_time: 30
  queue_limit: 0
  queue_sleep_time: 5
  web: True
  port: 6980
  host: 192.168.1.238
  web_root: 
  allow_delete_files: False
  add_columns_from_log: False
  add_complete_column: False
  debug: False
  manual_mode: False
  diagnose_errors: False
2024-06-24 00:26:58 | ℹ️ INFO     | ffmpeg version "4.4.2-0ubuntu0.22.04.1" found
2024-06-24 00:26:58 | ℹ️ INFO     | ffprobe version "4.4.2-0ubuntu0.22.04.1" found
2024-06-24 00:26:58 | ℹ️ INFO     | Start porndb scene watcher.... watching: /media/watch
Namer version: v1.18.9
Built on: 2024-06-19T05:46:20Z
Git Hash: 69848b41f351fcbd0cc853daae8922f6323b4189
2024-06-24 00:26:58 | ℹ️ INFO     | Moving /media/watch/PerfectFuckingStrangers.24.05.25.Scarlett.Sommers.XXX.480p.MP4-XXX[XC] to /media/work/PerfectFuckingStrangers.24.05.25.Scarlett.Sommers.XXX.480p.MP4-XXX[XC] for processing
2024-06-24 00:26:58 | ℹ️ INFO     | Processing: /media/work/PerfectFuckingStrangers.24.05.25.Scarlett.Sommers.XXX.480p.MP4-XXX[XC]
2024-06-24 00:26:58 | ℹ️ INFO     | Calculating phash for file "/media/work/PerfectFuckingStrangers.24.05.25.Scarlett.Sommers.XXX.480p.MP4-XXX[XC]/perfectfuckingstrangers.24.05.25.scarlett.sommers.480p.mp4"`
```

**Comment by DirtyRacer1337** [comment]
https://github.com/ThePornDatabase/namer/blob/main/install_instructions.md#unraid
